<?xml version="1.0" encoding="utf-8"?><Database Name="ATM2" Class="ATMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WILLY-LAPTOP\SQLEXPRESS;Initial Catalog=ATM2;User ID=net;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ATM2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SIN" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DateAccountCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Transaction]" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AmountTransferred" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfTransaction" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TransactionType" Member="TransactionTypes">
    <Type Name="TransactionType">
      <Column Name="TransactionTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionType" Member="TransactionType1" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>