
#
#	Makefile for solutions project (does nothing, just here so global build doesn't fail)
#

DEBUG = -g
CC = qcc
LD = qcc

TARGET = -Vgcc_ntox86
#TARGET = -Vgcc_ntoppcbe

CFLAGS += $(DEBUG) $(TARGET)
LDFLAGS+= $(DEBUG) $(TARGET)

BINS = 

all: 

clean:
	rm -f *.o $(BINS) *.tmp

